spring:
  application:
    name: shopping

app:
  cors:
    allowed-origin: ${FRONT_END_ORIGIN:http://localhost:5173}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_EXPIRATION:60}
